import type { ChannelConfig } from '@/types/sonification';

export const DEFAULT_WEATHER_CHANNEL: ChannelConfig = {
  streamId: 'weather',
  enabled: true,
  mode: 'pattern',
  synthType: 'Synth',
  synthOptions: { oscillator: { type: 'sine' } },
  mappings: [
    {
      sourceField: 'feelsLike',
      targetParam: 'patternSelect',
      curve: 'step',
      inputRange: [0, 100],
      outputRange: [0, 2],
      invert: false,
    },
    {
      sourceField: 'clouds',
      targetParam: 'noiseVolume',
      curve: 'linear',
      inputRange: [0, 100],
      outputRange: [-60, 0],
      invert: false,
    },
  ],
  effects: [],
  volume: 0,
  pan: 0,
  mute: false,
  solo: false,
  behaviorType: 'ambient',
  ambientMode: 'arpeggio',
  smoothingMs: 1200,
  preMapWindow: 1,
  preMapStatistic: 'mean',
  preMapChangeThreshold: 0,
  preMapDerivative: false,
  preMapPercentileClamp: 100,
  alertTier: 'advisory',
  beaconThreshold: 0,
  beaconPeriodicSec: 0,
  beaconOnExtrema: false,
  eventTriggerThreshold: 0,
  eventBurstCap: 0,
  eventBurstWindowMs: 1200,
  eventArticulation: 'neutral',
  hybridAccent: 0.6,
  sampleSource: 'rain',
  samplePlaybackRateMin: 0.8,
  samplePlaybackRateMax: 1.2,
  sampleDensity: 1.2,
  sampleFilterCutoff: 2200,
  sampleReverbSend: 0.25,
  patternType: 'upDown',
};

export const DEFAULT_FLIGHTS_CHANNEL: ChannelConfig = {
  streamId: 'flights',
  enabled: false,
  mode: 'continuous',
  synthType: 'Synth',
  synthOptions: {
    oscillator: { type: 'sine' },
    envelope: { attack: 0.1, decay: 0.2, sustain: 0.5, release: 0.8 },
  },
  mappings: [
    {
      sourceField: 'frequency',
      targetParam: 'frequency',
      curve: 'linear',
      inputRange: [110, 880],
      outputRange: [110, 880],
      invert: false,
    },
  ],
  effects: [],
  volume: -20,
  pan: 0,
  mute: false,
  solo: false,
  behaviorType: 'ambient',
  ambientMode: 'sustain',
  smoothingMs: 800,
  preMapWindow: 1,
  preMapStatistic: 'mean',
  preMapChangeThreshold: 0,
  preMapDerivative: false,
  preMapPercentileClamp: 100,
  alertTier: 'advisory',
  beaconThreshold: 0,
  beaconPeriodicSec: 0,
  beaconOnExtrema: false,
  eventTriggerThreshold: 0,
  eventBurstCap: 0,
  eventBurstWindowMs: 1200,
  eventArticulation: 'neutral',
  hybridAccent: 0.6,
  sampleSource: 'wind',
  samplePlaybackRateMin: 0.75,
  samplePlaybackRateMax: 1.1,
  sampleDensity: 0.8,
  sampleFilterCutoff: 1800,
  sampleReverbSend: 0.35,
  entityField: 'flightId',
};

export const DEFAULT_WIKIPEDIA_CHANNEL: ChannelConfig = {
  streamId: 'wikipedia',
  enabled: false,
  mode: 'triggered',
  synthType: 'Synth',
  synthOptions: {
    oscillator: { type: 'sine' },
    envelope: { attack: 0.01, decay: 0.2, sustain: 0.1, release: 0.1 },
  },
  mappings: [
    {
      sourceField: 'titleLength',
      targetParam: 'scaleIndex',
      curve: 'linear',
      inputRange: [0, 50],
      outputRange: [0, 12],
      invert: false,
    },
    {
      sourceField: 'absLengthDelta',
      targetParam: 'velocity',
      curve: 'exponential',
      inputRange: [0, 500],
      outputRange: [0.05, 1],
      invert: false,
    },
  ],
  effects: [],
  volume: 1,
  pan: 0,
  mute: false,
  solo: false,
  behaviorType: 'event',
  eventCooldownMs: 160,
  preMapWindow: 3,
  preMapStatistic: 'median',
  preMapChangeThreshold: 0,
  preMapDerivative: false,
  preMapPercentileClamp: 98,
  alertTier: 'abnormal',
  beaconThreshold: 0.8,
  beaconPeriodicSec: 0,
  beaconOnExtrema: true,
  eventTriggerThreshold: 0.08,
  eventBurstCap: 4,
  eventBurstWindowMs: 1500,
  eventArticulation: 'neutral',
  hybridAccent: 0.6,
  sampleSource: 'vinyl',
  samplePlaybackRateMin: 0.9,
  samplePlaybackRateMax: 1.4,
  sampleDensity: 2.2,
  sampleFilterCutoff: 3500,
  sampleReverbSend: 0.15,
};

export const DEFAULT_RSS_CHANNEL: ChannelConfig = {
  streamId: 'rss',
  enabled: false, // Off by default — user can enable
  mode: 'triggered',
  synthType: 'PluckSynth',
  synthOptions: {},
  mappings: [
    {
      sourceField: 'titleLength',
      targetParam: 'scaleIndex',
      curve: 'linear',
      inputRange: [0, 80],
      outputRange: [0, 12],
      invert: false,
    },
    {
      sourceField: 'contentLength',
      targetParam: 'velocity',
      curve: 'logarithmic',
      inputRange: [0, 1000],
      outputRange: [0.1, 0.8],
      invert: false,
    },
  ],
  effects: [],
  volume: -5,
  pan: -0.3,
  mute: false,
  solo: false,
  behaviorType: 'event',
  eventCooldownMs: 220,
  preMapWindow: 3,
  preMapStatistic: 'median',
  preMapChangeThreshold: 0,
  preMapDerivative: false,
  preMapPercentileClamp: 98,
  alertTier: 'advisory',
  beaconThreshold: 0.85,
  beaconPeriodicSec: 0,
  beaconOnExtrema: false,
  eventTriggerThreshold: 0.04,
  eventBurstCap: 3,
  eventBurstWindowMs: 1400,
  eventArticulation: 'soft',
  hybridAccent: 0.6,
  sampleSource: 'chimes',
  samplePlaybackRateMin: 0.9,
  samplePlaybackRateMax: 1.3,
  sampleDensity: 1.8,
  sampleFilterCutoff: 4200,
  sampleReverbSend: 0.2,
};

export const DEFAULT_STOCKS_CHANNEL: ChannelConfig = {
  streamId: 'stocks',
  enabled: false, // Off by default — needs FINNHUB_API_KEY
  mode: 'triggered',
  synthType: 'MembraneSynth',
  synthOptions: {},
  mappings: [
    {
      sourceField: 'priceDeltaPct',
      targetParam: 'velocity',
      curve: 'exponential',
      inputRange: [0, 5],
      outputRange: [0.1, 1],
      invert: false,
    },
    {
      sourceField: 'direction',
      targetParam: 'scaleIndex',
      curve: 'step',
      inputRange: [0, 1],
      outputRange: [0, 4],
      invert: false,
    },
  ],
  effects: [],
  volume: -10,
  pan: 0.3,
  mute: false,
  solo: false,
  behaviorType: 'event',
  eventCooldownMs: 180,
  preMapWindow: 5,
  preMapStatistic: 'mean',
  preMapChangeThreshold: 0,
  preMapDerivative: false,
  preMapPercentileClamp: 97,
  alertTier: 'critical',
  beaconThreshold: 0.9,
  beaconPeriodicSec: 0,
  beaconOnExtrema: true,
  eventTriggerThreshold: 0.1,
  eventBurstCap: 5,
  eventBurstWindowMs: 1500,
  sampleSource: 'vinyl',
  samplePlaybackRateMin: 0.85,
  samplePlaybackRateMax: 1.5,
  sampleDensity: 2.4,
  sampleFilterCutoff: 2800,
  sampleReverbSend: 0.12,
  eventArticulation: 'punchy',
  hybridAccent: 0.6,
};

export const ALL_DEFAULT_CHANNELS: ChannelConfig[] = [
  DEFAULT_WEATHER_CHANNEL,
  DEFAULT_FLIGHTS_CHANNEL,
  DEFAULT_WIKIPEDIA_CHANNEL,
  DEFAULT_RSS_CHANNEL,
  DEFAULT_STOCKS_CHANNEL,
];
